version: '2'

# Docker compose to test locally
services:
  site:
    build:
      context: .
    ports:
      - "127.0.0.1:5000:5000"
    volumes:
      - ./:/static
    command: python -m src.main
    networks:
      - default

networks:
  default:
    name: localtest-net
