version: '2'

services:
  site:
    image: static_site
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    container_name: jonny
    volumes:
      - .:/static
    networks:
      - default

networks:
  default:
    name: planet_telex
    driver: bridge
volumes:
  static:
