name: Deploy newest version

on:
  push:
    branches:
      - main
  workflow_dispatch:
    user:
      - benchungiscool

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy new config
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: cd ~/projects/personal-site && git pull && docker build -t personal-site:latest .

      - name: Trigger Target Repository
        uses: appleboy/ssh-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const response = await octokit.repos.createDispatchEvent({
              owner: 'benchungiscool',
              repo: 'infra',
              event_type: 'deploy-new-containers'
            });
            console.log(response.data);