name: Deploy newest version

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH
        run: |
          mkdir ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Pull latest changes
        run: ssh ${{ secrets.SERVER_IP }} 'cd ~/personal-site && git pull'

      - name: Start server
        run: ssh ${{ secrets.SERVER_IP  }} 'cd ~/personal-site && ./start.sh'
